const CartActionTypes = {
    TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
    ADD_BIKE_ITEM: "ADD_BIKE_ITEM",
    ADD_APPAREL_ITEM: "ADD_APPAREL_ITEM",
    CLEAR_BIKE_ITEM_FROM_CART: "CLEAR_BIKE_ITEM_FROM_CART",
    CLEAR_APPAREL_ITEM_FROM_CART: "CLEAR_APPAREL_ITEM_FROM_CART",
    REMOVE_BIKE_ITEM: "REMOVE_BIKE_ITEM",
    REMOVE_APPAREL_ITEM: "REMOVE_APPAREL_ITEM",
    CHECKOUT: "CHECKOUT"
}

export default CartActionTypes;