const CatalogActionTypes = {
    GET_HOVER_ITEM: "GET_HOVER_ITEM",
    FETCH_BIKES: "FETCH_BIKES",
    INIT_SELECTED_ITEM: "INIT_SELECTED_ITEM",
    FETCH_BIKE_DETAILS: "FETCH_BIKE_DETAILS"
}

export default CatalogActionTypes;